set nocompatible
filetype off

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'gregsexton/gitv'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'kana/vim-submode'

" Language Server Protocol
Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'scrooloose/nerdtree'
call plug#end()

" ファイルエンコードの設定
set enc=utf-8
set fenc=utf-8
set fencs=utf-8,iso-2022-jp,euc-jp,sjis,jis
set fileformats=unix,dos,mac

set number          " 行表示
set relativenumber  " 相対的な行表示
set showtabline=2   " タブページ常に表示
set noswapfile      " スワップファイル作らない
set nobackup        " バックアップファイル作らない
set showmatch       " 対応する括弧の表示
set matchtime=1     " 対応する括弧の表示を0.1*1秒に

" デフォルトインデント
set autoindent smartindent
set shiftwidth=4
set expandtab
set tabstop=4
set backspace=indent,eol,start  " Backspaceで色々削除可能
" 不可視文字表示
set list
set listchars=tab:\|\ ,trail:-
set whichwrap=b,s,h,l           " カーソルが行頭，行末で止まらない

" ファイルタイプ別設定
filetype on
filetype indent on
filetype plugin on
syntax on                       " syntaxカラー有効
syntax sync fromstart
set background=dark
colorscheme desert
set nrformats=alpha,octal,hex     " Ctrl+A, Ctrl+Xの加算減算で認識する基数
set wildmode=list,full            " exコマンド時，Tabで補完候補一覧
set undolevels=10000              " Undoの回数制限

set diffopt=filler,vertical
" ステータスラインの設定
set statusline&
set statusline=%<%F\ %m%r%h%w%y%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}[POS=%l,%v,%p%%]
set statusline+=%{fugitive#statusline()}
set laststatus=2
set showcmd               " 入力中のコマンド表示
setlocal bufhidden=delete " バッファ閉じた時に削除
set clipboard=unnamed,autoselect "無名レジスタを*レジスタにも入るように

cnoremap <C-a> <Home>
"" コマンドモードの設定
" 一文字戻る
cnoremap <C-b> <Left>
" カーソルの下の文字を削除
cnoremap <C-d> <Del>
" 行末へ移動
cnoremap <C-e> <End>
" 一文字進む
cnoremap <C-f> <Right>
" コマンドライン履歴を一つ進む
cnoremap <C-n> <Down>
" コマンドライン履歴を一つ戻る
cnoremap <C-p> <Up>
" 前の単語へ移動
cnoremap <M-b> <S-Left>
" 次の単語へ移動
cnoremap <M-f> <S-Right>

nmap <leader>t :terminal ++close bash --login<CR>

source ~/dotfiles/vim/vimrc.ft-vim.vim
source ~/dotfiles/vim/vimrc.ft-ruby.vim
source ~/dotfiles/vim/vimrc.ft-ts.vim

source ~/dotfiles/vim/vimrc.gitv.vim
source ~/dotfiles/vim/vimrc.ctrlp.vim
source ~/dotfiles/vim/vimrc.submode.vim
source ~/dotfiles/vim/vimrc.coc.vim
source ~/dotfiles/vim/vimrc.nerdtree.vim

if filereadable(".vimrc.project.vim")
  source .vimrc.project.vim
endif
